name: build_apk_workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: build-apk
        run: ./gradlew assembleDebug

      - name: upload-apk
        uses: actions/upload-artifact@v2
        with:
          name: Build 0.1 apk
          path: app/build/outputs/apk/debug/app-debug.apk


  unit_test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run unit test
        run: ./gradlew test

      - name: upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: testingResultReport
          path: app/build/reports/tests/testDebugUnitTest/index.html
