name: build_apk_workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: setup-java
      - uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: build-apk
        run: gradlew assembleDebug

      - name: upload-apk
      - uses: actions/upload-artifact@v2
        with:
            path: app/build/outputs/apk/debug/app-debug.apk
